import React from 'react';
import { MenuItem } from '@sketchpixy/rubix';

function langClick(lang, isTo) {
  this.setState(isTo ? { langTo: lang } : { langFrom: lang });
}

export const languageList = [
	{ value: "af", label: "af"},
	{ value: "ar-AE", label: "ar (AE)"},
	{ value: "ar-BH", label: "ar (BH)"},
	{ value: "ar-DZ", label: "ar (DZ)"},
	{ value: "ar-EG", label: "ar (EG)"},
	{ value: "ar-IQ", label: "ar (IQ)"},
	{ value: "ar-JO", label: "ar (JO)"},
	{ value: "ar-KW", label: "ar (KW)"},
	{ value: "ar-LB", label: "ar (LB)"},
	{ value: "ar-LY", label: "ar (LY)"},
	{ value: "ar-MA", label: "ar (MA)"},
	{ value: "ar-OM", label: "ar (OM)"},
	{ value: "ar-QA", label: "ar (QA)"},
	{ value: "ar-SA", label: "ar (SA)"},
	{ value: "ar-SY", label: "ar (SY)"},
	{ value: "ar-TN", label: "ar (TN)"},
	{ value: "ar-YE", label: "ar (YE)"},
	{ value: "be", label: "be"},
	{ value: "bg", label: "bg"},
	{ value: "ca", label: "ca"},
	{ value: "cs", label: "cs"},
	{ value: "da", label: "da"},
	{ value: "de", label: "de"},
	{ value: "de-AT", label: "de (AT)"},
	{ value: "de-CH", label: "de (CH)"},
	{ value: "de-LI", label: "de (LI)"},
	{ value: "de-LU", label: "de (LU)"},
	{ value: "el", label: "el"},
	{ value: "en", label: "en"},
	{ value: "en-AU", label: "en (AU)"},
	{ value: "en-BZ", label: "en (BZ)"},
	{ value: "en-CA", label: "en (CA)"},
	{ value: "en-EG", label: "en (EG)"},
	{ value: "en-GB", label: "en (GB)"},
	{ value: "en-IE", label: "en (IE)"},
	{ value: "en-JM", label: "en (JM)"},
	{ value: "en-NZ", label: "en (NZ)"},
	{ value: "en-TT", label: "en (TT)"},
	{ value: "en-US", label: "en (US)"},
	{ value: "en-ZA", label: "en (ZA)"},
	{ value: "es", label: "es"},
	{ value: "es-AR", label: "es (AR)"},
	{ value: "es-BO", label: "es (BO)"},
	{ value: "es-CL", label: "es (CL)"},
	{ value: "es-CO", label: "es (CO)"},
	{ value: "es-CR", label: "es (CR)"},
	{ value: "es-DO", label: "es (DO)"},
	{ value: "es-EC", label: "es (EC)"},
	{ value: "es-GT", label: "es (GT)"},
	{ value: "es-HN", label: "es (HN)"},
	{ value: "es-MX", label: "es (MX)"},
	{ value: "es-NI", label: "es (NI)"},
	{ value: "es-PA", label: "es (PA)"},
	{ value: "es-PE", label: "es (PE)"},
	{ value: "es-PR", label: "es (PR)"},
	{ value: "es-PY", label: "es (PY)"},
	{ value: "es-SV", label: "es (SV)"},
	{ value: "es-UY", label: "es (UY)"},
	{ value: "es-VE", label: "es (VE)"},
	{ value: "et", label: "et"},
	{ value: "eu", label: "eu"},
	{ value: "fa", label: "fa"},
	{ value: "fi", label: "fi"},
	{ value: "fo", label: "fo"},
	{ value: "fr", label: "fr"},
	{ value: "fr-BE", label: "fr (BE)"},
	{ value: "fr-CA", label: "fr (CA)"},
	{ value: "fr-CH", label: "fr (CH)"},
	{ value: "fr-LU", label: "fr (LU)"},
	{ value: "gd", label: "gd"},
	{ value: "gd-IE", label: "gd (IE)"},
	{ value: "he", label: "he"},
	{ value: "hi", label: "hi"},
	{ value: "hr", label: "hr"},
	{ value: "hu", label: "hu"},
	{ value: "id", label: "id"},
	{ value: "is", label: "is"},
	{ value: "it", label: "it"},
	{ value: "it-CH", label: "it (CH)"},
	{ value: "ja", label: "ja"},
	{ value: "ji", label: "ji"},
	{ value: "ko", label: "ko"},
	{ value: "lt", label: "lt"},
	{ value: "lv", label: "lv"},
	{ value: "mk", label: "mk"},
	{ value: "mt", label: "mt"},
	{ value: "nl", label: "nl"},
	{ value: "nl-BE", label: "nl (BE)"},
	{ value: "no", label: "no"},
	{ value: "pl", label: "pl"},
	{ value: "pt", label: "pt"},
	{ value: "pt-BR", label: "pt (BR)"},
	{ value: "rm", label: "rm"},
	{ value: "ro", label: "ro"},
	{ value: "ro-MO", label: "ro (MO)"},
	{ value: "ru", label: "ru"},
	{ value: "ru-MI", label: "ru (MI)"},
	{ value: "sb", label: "sb"},
	{ value: "sk", label: "sk"},
	{ value: "sl", label: "sl"},
	{ value: "sq", label: "sq"},
	{ value: "sr", label: "sr"},
	{ value: "sv", label: "sv"},
	{ value: "sv-FI", label: "sv (FI)"},
	{ value: "sx", label: "sx"},
	{ value: "sz", label: "sz"},
	{ value: "th", label: "th"},
	{ value: "tn", label: "tn"},
	{ value: "tr", label: "tr"},
	{ value: "ts", label: "ts"},
	{ value: "uk", label: "uk"},
	{ value: "ur", label: "ur"},
	{ value: "ve", label: "ve"},
	{ value: "vi", label: "vi"},
	{ value: "xh", label: "xh"},
	{ value: "zh-CN", label: "zh (CN)"},
	{ value: "zh-HK", label: "zh (HK)"},
	{ value: "zh-SG", label: "zh (SG)"},
	{ value: "zh-TW", label: "zh (TW)"},
	{ value: "zu", label: "zu"},
];

export default function renderLanguajeDropdown(isTo) {
  const langs = [
    'af',
    'ar-AE',
    'ar-BH',
    'ar-DZ',
    'ar-EG',
    'ar-IQ',
    'ar-JO',
    'ar-KW',
    'ar-LB',
    'ar-LY',
    'ar-MA',
    'ar-OM',
    'ar-QA',
    'ar-SA',
    'ar-SY',
    'ar-TN',
    'ar-YE',
    'be',
    'bg',
    'ca',
    'cs',
    'da',
    'de',
    'de-AT',
    'de-CH',
    'de-LI',
    'de-LU',
    'el',
    'en',
    'en-AU',
    'en-BZ',
    'en-CA',
    'en-EG',
    'en-GB',
    'en-IE',
    'en-JM',
    'en-NZ',
    'en-TT',
    'en-US',
    'en-ZA',
    'es',
    'es-AR',
    'es-BO',
    'es-CL',
    'es-CO',
    'es-CR',
    'es-DO',
    'es-EC',
    'es-GT',
    'es-HN',
    'es-MX',
    'es-NI',
    'es-PA',
    'es-PE',
    'es-PR',
    'es-PY',
    'es-SV',
    'es-UY',
    'es-VE',
    'et',
    'eu',
    'fa',
    'fi',
    'fo',
    'fr',
    'fr-BE',
    'fr-CA',
    'fr-CH',
    'fr-LU',
    'gd',
    'gd-IE',
    'he',
    'hi',
    'hr',
    'hu',
    'id',
    'is',
    'it',
    'it-CH',
    'ja',
    'ji',
    'ko',
    'lt',
    'lv',
    'mk',
    'mt',
    'nl',
    'nl-BE',
    'no',
    'pl',
    'pt',
    'pt-BR',
    'rm',
    'ro',
    'ro-MO',
    'ru',
    'ru-MI',
    'sb',
    'sk',
    'sl',
    'sq',
    'sr',
    'sv',
    'sv-FI',
    'sx',
    'sz',
    'th',
    'tn',
    'tr',
    'ts',
    'uk',
    'ur',
    've',
    'vi',
    'xh',
    'zh-CN',
    'zh-HK',
    'zh-SG',
    'zh-TW',
    'zu',
  ];
  return langs.map(lang => (<MenuItem
    key={lang}
    onClick={langClick.bind(this, lang, isTo)}
  >{lang}
  </MenuItem>));
}
