const actionTypes = {
  // Audios
  ALL_AUDIOS: 'ALL_AUDIOS',
  SINGLE_AUDIO: 'SINGLE_AUDIO',
  CREATE_AUDIO: 'CREATE_AUDIO',
  EDIT_AUDIO: 'EDIT_AUDIO',
  REMOVE_AUDIO: 'REMOVE_AUDIO',
  // Exps
  ALL_EXPS: 'ALL_EXPS',
  SINGLE_EXP: 'SINGLE_EXP',
  CREATE_EXP: 'CREATE_EXP',
  EDIT_EXP: 'EDIT_EXP',
  REMOVE_EXP: 'REMOVE_EXP',
  // Posts
  ALL_POSTS: 'ALL_POSTS',
  SINGLE_POST: 'SINGLE_POST',
  CREATE_POST: 'CREATE_POST',
  EDIT_POST: 'EDIT_POST',
  REMOVE_POST: 'REMOVE_POST',
  // Prets
  ALL_PRETS: 'ALL_PRETS',
  SINGLE_PRET: 'SINGLE_PRET',
  CREATE_PRET: 'CREATE_PRET',
  EDIT_PRET: 'EDIT_PRET',
  REMOVE_PRET: 'REMOVE_PRET',
  // Tags
  ALL_TAGS: 'ALL_TAGS',
  SINGLE_TAG: 'SINGLE_TAG',
  CREATE_TAG: 'CREATE_TAG',
  EDIT_TAG: 'EDIT_TAG',
  REMOVE_TAG: 'REMOVE_TAG',
  // Users
  ALL_USERS: 'ALL_USERS',
  SINGLE_USER: 'SINGLE_USER',
  CREATE_USER: 'CREATE_USER',
  EDIT_USER: 'EDIT_USER',
  REMOVE_USER: 'REMOVE_USER',
  // News
  ALL_NEWS: 'ALL_NEWS',
};

module.exports = {
  ...actionTypes,
};
